# Custom Language File for Launcher Customizer

[ejs.app]
title = "호백타운2"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/hobackTown"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/hobackTown"
supportLink = "https://github.com/mchlauncher/hobackTown/issues"

[ejs.welcome]
welcomeHeader = "호백타운2"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."